[package]
name = "hyperlane-register-module"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Sovereign Labs <info@sovereign.xyz>"]
publish = false
rust-version = "1.81"

[dependencies]
anyhow = { version = "1.0.95" }
borsh = { version = "1", features = ["rc"] }
serde = { version = "1.0.192", features = ["derive", "rc"] }
serde_json = { version = "1.0" }

sov-modules-api = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "19509c52a85b8a621b1618d848bb5c13fef51901" }
sov-hyperlane-integration = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "19509c52a85b8a621b1618d848bb5c13fef51901" }
sov-accounts = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "19509c52a85b8a621b1618d848bb5c13fef51901" }

[dev-dependencies]
sov-test-utils = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "19509c52a85b8a621b1618d848bb5c13fef51901" }

[build-dependencies]
serde = { version = "1.0.192", features = ["derive", "rc"] }
serde_json = { version = "1.0" }
